base: &base
  adapter: postgresql
  encoding: utf8

development:
  database: content_scrapper_development
  <<: *base
    
test:
  database: content_scrapper_test<%= ENV['TEST_ENV_NUMBER'] %>
  <<: *base
